import React from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  Platform,
  useWindowDimensions,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as Animatable from 'react-native-animatable';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { RootStackParamList } from '../types';
import { theme } from '../constants/theme';
import { GradientButton } from '../components/ui';

type Props = NativeStackScreenProps<RootStackParamList, 'Landing'>;

const FEATURES = [
  { num: '01', title: 'AI Yoga Coach', desc: 'Real-time pose detection and correction with personalized feedback' },
  { num: '02', title: 'Wellness Chat', desc: 'Instant guidance on yoga, fitness, and nutrition from your AI coach' },
  { num: '03', title: 'Custom Plans', desc: 'Workout and meal plans generated by AI based on your goals' },
];

const LandingScreen: React.FC<Props> = ({ navigation }) => {
  const { width } = useWindowDimensions();
  const isDesktop = width >= 1024;

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.scrollContent}
      showsVerticalScrollIndicator={false}
    >
      {/* Header */}
      <View style={styles.header}>
        <View style={styles.headerInner}>
          <Text style={styles.logo}>Yogifi</Text>
          <View style={styles.headerRight}>
            <TouchableOpacity onPress={() => navigation.navigate('Login')}>
              <Text style={styles.signInLink}>Sign In</Text>
            </TouchableOpacity>
            <GradientButton
              title="Get Started"
              onPress={() => navigation.navigate('Register')}
              variant="dark"
              size="sm"
            />
          </View>
        </View>
      </View>

      <View style={styles.inner}>
        {/* Hero */}
        <View style={[styles.heroSection, isDesktop && styles.heroSectionDesktop]}>
          <Animatable.View animation="fadeIn" duration={500}>
            <Text style={[styles.heroTitle, isDesktop && styles.heroTitleDesktop]}>
              Your Wellness,{'\n'}Guided by AI
            </Text>
          </Animatable.View>

          <Animatable.View animation="fadeIn" delay={150} duration={500}>
            <Text style={styles.heroSubtitle}>
              AI-powered yoga coaching, personalized fitness plans, and nutrition guidance — all in one platform.
            </Text>
          </Animatable.View>

          <Animatable.View animation="fadeIn" delay={300} duration={500} style={styles.heroCTAs}>
            <GradientButton
              title="Start Free Trial"
              onPress={() => navigation.navigate('Register')}
              variant="dark"
              size="lg"
              style={styles.heroPrimaryBtn}
            />
          </Animatable.View>
        </View>

        {/* Social Proof */}
        <Animatable.View animation="fadeIn" delay={400} duration={500} style={styles.proofSection}>
          <Text style={styles.proofText}>
            10K+ members{' '}<Text style={styles.proofDot}>{'\u00B7'}</Text>{' '}4.9 rating{' '}<Text style={styles.proofDot}>{'\u00B7'}</Text>{' '}95% success rate
          </Text>
        </Animatable.View>

        {/* Features */}
        <View style={styles.featuresSection}>
          <Animatable.View animation="fadeIn" duration={500}>
            <Text style={styles.sectionLabel}>WHAT WE OFFER</Text>
          </Animatable.View>

          {FEATURES.map((feature, i) => (
            <Animatable.View key={feature.num} animation="fadeIn" delay={i * 100} duration={500}>
              <View style={[styles.featureRow, isDesktop && styles.featureRowDesktop]}>
                <Text style={styles.featureNum}>{feature.num}</Text>
                <View style={styles.featureContent}>
                  <Text style={styles.featureTitle}>{feature.title}</Text>
                  <Text style={styles.featureDesc}>{feature.desc}</Text>
                </View>
              </View>
              {i < FEATURES.length - 1 && <View style={styles.featureSeparator} />}
            </Animatable.View>
          ))}
        </View>

        {/* CTA Section - Dark */}
        <View style={styles.ctaSection}>
          <Animatable.View animation="fadeIn" duration={500} style={styles.ctaInner}>
            <Text style={styles.ctaTitle}>Start your wellness{'\n'}journey today</Text>
            <Text style={styles.ctaSubtitle}>
              Join thousands transforming their health with AI-powered guidance.
            </Text>
            <GradientButton
              title="Get Started Free"
              onPress={() => navigation.navigate('Register')}
              variant="accent"
              size="lg"
              style={styles.ctaButton}
            />
            <Text style={styles.ctaFootnote}>No credit card required</Text>
          </Animatable.View>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerLogo}>Yogifi</Text>
          <Text style={styles.footerText}>AI-powered wellness platform</Text>
          <View style={styles.footerLinks}>
            <TouchableOpacity><Text style={styles.footerLink}>Privacy</Text></TouchableOpacity>
            <TouchableOpacity><Text style={styles.footerLink}>Terms</Text></TouchableOpacity>
            <TouchableOpacity><Text style={styles.footerLink}>Contact</Text></TouchableOpacity>
          </View>
        </View>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContent: {
    flexGrow: 1,
  },
  inner: {
    maxWidth: 800,
    alignSelf: 'center',
    width: '100%',
  },

  // Header
  header: {
    position: Platform.OS === 'web' ? ('sticky' as any) : 'relative',
    top: 0,
    zIndex: 100,
    backgroundColor: 'rgba(255, 255, 255, 0.97)',
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.borderLight,
  },
  headerInner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.screen,
    paddingVertical: 16,
    maxWidth: 800,
    alignSelf: 'center',
    width: '100%',
  },
  logo: {
    ...theme.typography.h3,
    color: theme.colors.text,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  signInLink: {
    ...theme.typography.bodyMedium,
    color: theme.colors.text,
  },

  // Hero
  heroSection: {
    paddingHorizontal: theme.spacing.screen,
    paddingTop: 96,
    paddingBottom: 48,
  },
  heroSectionDesktop: {
    paddingTop: 128,
    paddingBottom: 64,
  },
  heroTitle: {
    ...theme.typography.hero,
    color: theme.colors.text,
    marginBottom: 24,
  },
  heroTitleDesktop: {
    ...theme.typography.display,
  },
  heroSubtitle: {
    ...theme.typography.bodyLarge,
    color: theme.colors.textSecondary,
    marginBottom: 40,
    maxWidth: 520,
  },
  heroCTAs: {
    marginBottom: 16,
  },
  heroPrimaryBtn: {
    alignSelf: 'flex-start',
    minWidth: 200,
  },

  // Social Proof
  proofSection: {
    paddingHorizontal: theme.spacing.screen,
    paddingBottom: 96,
  },
  proofText: {
    ...theme.typography.bodySm,
    color: theme.colors.textTertiary,
  },
  proofDot: {
    color: theme.colors.primaryLight,
  },

  // Features
  featuresSection: {
    paddingHorizontal: theme.spacing.screen,
    paddingBottom: 96,
  },
  sectionLabel: {
    ...theme.typography.caption,
    color: theme.colors.primary,
    marginBottom: 48,
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 24,
    paddingVertical: 32,
  },
  featureRowDesktop: {
    gap: 40,
  },
  featureNum: {
    ...theme.typography.h1,
    color: theme.colors.primaryLight,
  },
  featureContent: {
    flex: 1,
    paddingTop: 8,
  },
  featureTitle: {
    ...theme.typography.h3,
    color: theme.colors.text,
    marginBottom: 8,
  },
  featureDesc: {
    ...theme.typography.body,
    color: theme.colors.textTertiary,
  },
  featureSeparator: {
    height: 1,
    backgroundColor: theme.colors.borderLight,
  },

  // CTA - Dark
  ctaSection: {
    backgroundColor: '#1a1a1a',
    paddingVertical: 96,
    paddingHorizontal: theme.spacing.screen,
  },
  ctaInner: {
    alignItems: 'center',
    maxWidth: 480,
    alignSelf: 'center',
  },
  ctaTitle: {
    ...theme.typography.h2,
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 16,
  },
  ctaSubtitle: {
    ...theme.typography.body,
    color: 'rgba(255, 255, 255, 0.6)',
    textAlign: 'center',
    marginBottom: 40,
  },
  ctaButton: {
    minWidth: 220,
    marginBottom: 16,
  },
  ctaFootnote: {
    ...theme.typography.bodySm,
    color: 'rgba(255, 255, 255, 0.4)',
  },

  // Footer
  footer: {
    alignItems: 'center',
    paddingVertical: 48,
    paddingHorizontal: theme.spacing.screen,
    borderTopWidth: 1,
    borderTopColor: theme.colors.borderLight,
  },
  footerLogo: {
    ...theme.typography.h3,
    color: theme.colors.text,
    marginBottom: 8,
  },
  footerText: {
    ...theme.typography.bodySm,
    color: theme.colors.textTertiary,
    marginBottom: 24,
  },
  footerLinks: {
    flexDirection: 'row',
    gap: 32,
  },
  footerLink: {
    ...theme.typography.bodySm,
    color: theme.colors.textSecondary,
  },
});

export default LandingScreen;
