import React from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  Platform,
  useWindowDimensions,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import * as Animatable from 'react-native-animatable';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { RootStackParamList } from '../types';
import { theme } from '../constants/theme';
import { GradientButton } from '../components/ui';
import FloatingOrb from '../components/3D/FloatingOrb';

type Props = NativeStackScreenProps<RootStackParamList, 'Landing'>;

const FEATURES = [
  { emoji: '\u{1F9D8}', title: 'AI Yoga Coach', description: 'Real-time pose detection and correction with personalized AI feedback' },
  { emoji: '\u{1F4AC}', title: 'Wellness Chat', description: 'Get instant advice on yoga, fitness, and nutrition from your AI coach' },
  { emoji: '\u{1F4AA}', title: 'Fitness Plans', description: 'Custom workout routines generated by AI based on your goals and level' },
  { emoji: '\u{1F957}', title: 'Diet Planning', description: 'Personalized meal plans tailored to your dietary preferences and goals' },
  { emoji: '\u{1F4CA}', title: 'Progress Tracking', description: 'Detailed analytics and insights to monitor your wellness journey' },
  { emoji: '\u{1F3AF}', title: 'Goal Setting', description: 'Set and achieve wellness milestones with AI-guided recommendations' },
];

const STEPS = [
  { num: '01', title: 'Create your account', desc: 'Sign up in seconds and tell us about your wellness goals' },
  { num: '02', title: 'Get your AI plan', desc: 'Receive personalized yoga, fitness, and nutrition plans' },
  { num: '03', title: 'Practice with AI', desc: 'Get real-time feedback during your yoga sessions' },
  { num: '04', title: 'Track & improve', desc: 'Monitor progress and let AI adapt your journey' },
];

const TESTIMONIALS = [
  { quote: 'Yogifi completely transformed my morning routine. The AI feedback is incredibly accurate.', name: 'Sarah K.', role: 'Yoga Enthusiast', stars: 5 },
  { quote: 'The personalized fitness plans are amazing. I\'ve seen more progress in 2 months than the past year.', name: 'James R.', role: 'Fitness Beginner', stars: 5 },
  { quote: 'Having an AI wellness coach available 24/7 has been a game-changer for my health journey.', name: 'Maya P.', role: 'Wellness Advocate', stars: 5 },
];

const STATS = [
  { value: '10K+', label: 'Active Members' },
  { value: '500K+', label: 'Sessions Completed' },
  { value: '4.9', label: 'App Rating' },
  { value: '95%', label: 'Success Rate' },
];

const LandingScreen: React.FC<Props> = ({ navigation }) => {
  const { width } = useWindowDimensions();
  const isDesktop = width >= 1024;
  const isTablet = width >= 768;

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.scrollContent}
      showsVerticalScrollIndicator={false}
    >
      {/* Sticky Header */}
      <View style={styles.header}>
        <View style={styles.headerInner}>
          <Text style={styles.logo}>Yogifi</Text>
          <View style={styles.headerRight}>
            <TouchableOpacity onPress={() => navigation.navigate('Login')}>
              <Text style={styles.signInLink}>Sign In</Text>
            </TouchableOpacity>
            <GradientButton
              title="Get Started"
              onPress={() => navigation.navigate('Register')}
              variant="accent"
              size="sm"
            />
          </View>
        </View>
      </View>

      <View style={styles.inner}>
        {/* Hero Section */}
        <View style={[styles.heroSection, isDesktop && styles.heroSectionDesktop]}>
          <View style={[styles.heroTextArea, isDesktop && styles.heroTextAreaDesktop]}>
            <Animatable.View animation="fadeIn" duration={400}>
              <Text style={styles.eyebrow}>AI-POWERED WELLNESS</Text>
            </Animatable.View>

            <Animatable.View animation="fadeInUp" delay={100} duration={500}>
              <Text style={[styles.heroTitle, isDesktop && styles.heroTitleDesktop]}>
                Your Personal{'\n'}Wellness Coach
              </Text>
            </Animatable.View>

            <Animatable.View animation="fadeInUp" delay={200} duration={500}>
              <Text style={styles.heroSubtitle}>
                AI-powered yoga coaching, personalized fitness plans, and nutrition guidance — all in one platform designed for your wellness journey.
              </Text>
            </Animatable.View>

            <Animatable.View animation="fadeInUp" delay={300} duration={500} style={styles.heroCTAs}>
              <GradientButton
                title="Start Free Trial"
                onPress={() => navigation.navigate('Register')}
                variant="accent"
                size="lg"
                style={styles.heroPrimaryBtn}
              />
              <GradientButton
                title="Watch Demo"
                onPress={() => {}}
                variant="outline"
                size="lg"
                style={styles.heroSecondaryBtn}
              />
            </Animatable.View>

            <Animatable.View animation="fadeIn" delay={500} duration={400} style={styles.socialProof}>
              <View style={styles.avatarGroup}>
                {['#c9c1ea', '#aac7e2', '#f1bfd5', '#ffcdc1'].map((color, i) => (
                  <View key={i} style={[styles.avatar, { backgroundColor: color, marginLeft: i > 0 ? -10 : 0 }]} />
                ))}
              </View>
              <Text style={styles.socialProofText}>
                Join <Text style={styles.socialProofBold}>10,000+</Text> members on their wellness journey
              </Text>
            </Animatable.View>
          </View>

          {isDesktop && (
            <View style={styles.heroOrbContainer}>
              <FloatingOrb color="#c9c1ea" size={1.5} />
            </View>
          )}
        </View>

        {/* Features Section */}
        <View style={styles.featuresSection}>
          <Animatable.View animation="fadeIn" duration={400}>
            <Text style={styles.sectionLabel}>FEATURES</Text>
            <Text style={styles.sectionTitle}>
              Everything you need{'\n'}for your wellness
            </Text>
          </Animatable.View>

          <View style={[styles.featuresGrid, isDesktop && styles.featuresGridDesktop, isTablet && !isDesktop && styles.featuresGridTablet]}>
            {FEATURES.map((feature, i) => (
              <Animatable.View key={feature.title} animation="fadeInUp" delay={i * 80} duration={500} style={[styles.featureCard, isDesktop && styles.featureCardDesktop, isTablet && !isDesktop && styles.featureCardTablet]}>
                <View style={styles.featureIconWrap}>
                  <Text style={styles.featureEmoji}>{feature.emoji}</Text>
                </View>
                <Text style={styles.featureTitle}>{feature.title}</Text>
                <Text style={styles.featureDesc}>{feature.description}</Text>
              </Animatable.View>
            ))}
          </View>
        </View>

        {/* How It Works — Dark Section */}
        <View style={styles.howItWorksSection}>
          <Text style={styles.howItWorksLabel}>HOW IT WORKS</Text>
          <Text style={styles.howItWorksTitle}>
            Four simple steps to{'\n'}transform your wellness
          </Text>

          <View style={[styles.stepsGrid, isDesktop && styles.stepsGridDesktop]}>
            {STEPS.map((step, i) => (
              <Animatable.View key={step.num} animation="fadeInUp" delay={i * 100} duration={500} style={[styles.stepCard, isDesktop && styles.stepCardDesktop]}>
                <Text style={styles.stepNum}>{step.num}</Text>
                <Text style={styles.stepTitle}>{step.title}</Text>
                <Text style={styles.stepDesc}>{step.desc}</Text>
              </Animatable.View>
            ))}
          </View>
        </View>

        {/* Testimonials */}
        <View style={styles.testimonialsSection}>
          <Text style={styles.sectionLabel}>TESTIMONIALS</Text>
          <Text style={styles.sectionTitle}>Loved by thousands</Text>

          <ScrollView
            horizontal
            showsHorizontalScrollIndicator={false}
            contentContainerStyle={styles.testimonialsScroll}
          >
            {TESTIMONIALS.map((t, i) => (
              <Animatable.View key={i} animation="fadeInRight" delay={i * 100} duration={500} style={styles.testimonialCard}>
                <View style={styles.starsRow}>
                  {Array.from({ length: t.stars }).map((_, j) => (
                    <Ionicons key={j} name="star" size={16} color="#ffcdc1" />
                  ))}
                </View>
                <Text style={styles.testimonialQuote}>"{t.quote}"</Text>
                <View style={styles.testimonialAuthor}>
                  <View style={styles.testimonialAvatar}>
                    <Text style={styles.testimonialInitial}>{t.name[0]}</Text>
                  </View>
                  <View>
                    <Text style={styles.testimonialName}>{t.name}</Text>
                    <Text style={styles.testimonialRole}>{t.role}</Text>
                  </View>
                </View>
              </Animatable.View>
            ))}
          </ScrollView>
        </View>

        {/* Stats Section — Cream */}
        <View style={styles.statsSection}>
          <View style={[styles.statsGrid, isDesktop && styles.statsGridDesktop]}>
            {STATS.map((stat, i) => (
              <Animatable.View key={stat.label} animation="fadeInUp" delay={i * 80} duration={500} style={styles.statBlock}>
                <Text style={styles.statValue}>{stat.value}</Text>
                <Text style={styles.statLabel}>{stat.label}</Text>
              </Animatable.View>
            ))}
          </View>
        </View>

        {/* CTA Section */}
        <View style={styles.ctaSection}>
          <LinearGradient
            colors={theme.gradients.primary as any}
            start={{ x: 0, y: 0 }}
            end={{ x: 1, y: 1 }}
            style={styles.ctaCard}
          >
            <Text style={styles.ctaTitle}>Start your wellness{'\n'}journey today</Text>
            <Text style={styles.ctaSubtitle}>
              Join thousands of members transforming their health with AI-powered guidance.
            </Text>
            <GradientButton
              title="Get Started Free"
              onPress={() => navigation.navigate('Register')}
              variant="dark"
              size="lg"
              style={styles.ctaButton}
            />
            <Text style={styles.ctaFootnote}>No credit card required</Text>
          </LinearGradient>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerLogo}>Yogifi</Text>
          <Text style={styles.footerText}>AI-powered wellness platform</Text>
          <View style={styles.footerLinks}>
            <TouchableOpacity><Text style={styles.footerLink}>Privacy</Text></TouchableOpacity>
            <TouchableOpacity><Text style={styles.footerLink}>Terms</Text></TouchableOpacity>
            <TouchableOpacity><Text style={styles.footerLink}>Contact</Text></TouchableOpacity>
          </View>
        </View>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContent: {
    flexGrow: 1,
  },
  inner: {
    maxWidth: 1200,
    alignSelf: 'center',
    width: '100%',
  },

  // Header
  header: {
    position: Platform.OS === 'web' ? ('sticky' as any) : 'relative',
    top: 0,
    zIndex: 100,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.borderLight,
  },
  headerInner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.screen,
    paddingVertical: 16,
    maxWidth: 1200,
    alignSelf: 'center',
    width: '100%',
  },
  logo: {
    ...theme.typography.h3,
    color: theme.colors.text,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  signInLink: {
    ...theme.typography.bodyMedium,
    color: theme.colors.text,
  },

  // Hero
  heroSection: {
    paddingHorizontal: theme.spacing.screen,
    paddingTop: 80,
    paddingBottom: 80,
  },
  heroSectionDesktop: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 120,
    paddingBottom: 120,
  },
  heroTextArea: {
    flex: 1,
  },
  heroTextAreaDesktop: {
    flex: 1,
    paddingRight: 64,
  },
  eyebrow: {
    ...theme.typography.caption,
    color: theme.colors.primaryDark,
    marginBottom: 24,
  },
  heroTitle: {
    ...theme.typography.hero,
    color: theme.colors.text,
    marginBottom: 24,
  },
  heroTitleDesktop: {
    ...theme.typography.display,
  },
  heroSubtitle: {
    ...theme.typography.bodyLarge,
    color: theme.colors.textSecondary,
    marginBottom: 40,
    maxWidth: 560,
  },
  heroCTAs: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 40,
    flexWrap: 'wrap',
  },
  heroPrimaryBtn: {
    minWidth: 180,
  },
  heroSecondaryBtn: {
    minWidth: 160,
  },
  socialProof: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatarGroup: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  socialProofText: {
    ...theme.typography.bodySm,
    color: theme.colors.textTertiary,
  },
  socialProofBold: {
    fontFamily: 'DMSans_700Bold',
    color: theme.colors.text,
  },
  heroOrbContainer: {
    width: 400,
    height: 400,
  },

  // Features
  featuresSection: {
    paddingHorizontal: theme.spacing.screen,
    paddingVertical: 96,
  },
  sectionLabel: {
    ...theme.typography.caption,
    color: theme.colors.primaryDark,
    marginBottom: 16,
    textAlign: 'center',
  },
  sectionTitle: {
    ...theme.typography.h2,
    color: theme.colors.text,
    textAlign: 'center',
    marginBottom: 64,
  },
  featuresGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 24,
    justifyContent: 'center',
  },
  featuresGridDesktop: {
    gap: 32,
  },
  featuresGridTablet: {
    gap: 24,
  },
  featureCard: {
    width: '100%',
    backgroundColor: theme.colors.card,
    borderRadius: theme.radius.xl,
    padding: 32,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  featureCardDesktop: {
    width: '30%',
  },
  featureCardTablet: {
    width: '46%',
  },
  featureIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: theme.colors.primaryMuted,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  featureEmoji: {
    fontSize: 28,
  },
  featureTitle: {
    ...theme.typography.h4,
    color: theme.colors.text,
    marginBottom: 8,
  },
  featureDesc: {
    ...theme.typography.bodySm,
    color: theme.colors.textTertiary,
    lineHeight: 22,
  },

  // How It Works — Dark
  howItWorksSection: {
    backgroundColor: '#0a0a0a',
    paddingHorizontal: theme.spacing.screen,
    paddingVertical: 96,
  },
  howItWorksLabel: {
    ...theme.typography.caption,
    color: theme.colors.primaryDark,
    marginBottom: 16,
    textAlign: 'center',
  },
  howItWorksTitle: {
    ...theme.typography.h2,
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 64,
  },
  stepsGrid: {
    gap: 24,
    maxWidth: 800,
    alignSelf: 'center',
    width: '100%',
  },
  stepsGridDesktop: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    maxWidth: 1200,
    gap: 32,
  },
  stepCard: {
    padding: 32,
    borderRadius: theme.radius.xl,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  stepCardDesktop: {
    flex: 1,
    minWidth: '20%',
  },
  stepNum: {
    ...theme.typography.h1,
    color: theme.colors.primaryDark,
    marginBottom: 16,
  },
  stepTitle: {
    ...theme.typography.h4,
    color: '#ffffff',
    marginBottom: 8,
  },
  stepDesc: {
    ...theme.typography.bodySm,
    color: 'rgba(255, 255, 255, 0.6)',
    lineHeight: 22,
  },

  // Testimonials
  testimonialsSection: {
    paddingVertical: 96,
    paddingHorizontal: theme.spacing.screen,
  },
  testimonialsScroll: {
    paddingTop: 8,
    paddingBottom: 8,
    gap: 24,
  },
  testimonialCard: {
    width: 320,
    backgroundColor: theme.colors.card,
    borderRadius: theme.radius.xl,
    padding: 32,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  starsRow: {
    flexDirection: 'row',
    gap: 4,
    marginBottom: 16,
  },
  testimonialQuote: {
    ...theme.typography.body,
    color: theme.colors.text,
    marginBottom: 24,
    lineHeight: 26,
  },
  testimonialAuthor: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  testimonialAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.primaryMuted,
    justifyContent: 'center',
    alignItems: 'center',
  },
  testimonialInitial: {
    ...theme.typography.bodyMedium,
    color: theme.colors.primaryDark,
  },
  testimonialName: {
    ...theme.typography.bodySmMedium,
    color: theme.colors.text,
  },
  testimonialRole: {
    ...theme.typography.caption,
    color: theme.colors.textTertiary,
    textTransform: 'none',
    letterSpacing: 0,
    fontSize: 12,
  },

  // Stats — Cream
  statsSection: {
    backgroundColor: '#ece4c1',
    paddingHorizontal: theme.spacing.screen,
    paddingVertical: 80,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 40,
    maxWidth: 1000,
    alignSelf: 'center',
    width: '100%',
  },
  statsGridDesktop: {
    gap: 80,
  },
  statBlock: {
    alignItems: 'center',
    minWidth: 120,
  },
  statValue: {
    ...theme.typography.display,
    color: '#0a0a0a',
    marginBottom: 4,
  },
  statLabel: {
    ...theme.typography.bodySm,
    color: '#2d2d2d',
  },

  // CTA
  ctaSection: {
    paddingHorizontal: theme.spacing.screen,
    paddingVertical: 96,
  },
  ctaCard: {
    borderRadius: theme.radius['2xl'],
    paddingVertical: 80,
    paddingHorizontal: 40,
    alignItems: 'center',
  },
  ctaTitle: {
    ...theme.typography.h1,
    color: theme.colors.text,
    textAlign: 'center',
    marginBottom: 16,
  },
  ctaSubtitle: {
    ...theme.typography.bodyLarge,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginBottom: 40,
    maxWidth: 480,
  },
  ctaButton: {
    minWidth: 220,
    marginBottom: 16,
  },
  ctaFootnote: {
    ...theme.typography.bodySm,
    color: theme.colors.textTertiary,
  },

  // Footer
  footer: {
    alignItems: 'center',
    paddingVertical: 48,
    paddingHorizontal: theme.spacing.screen,
    borderTopWidth: 1,
    borderTopColor: theme.colors.borderLight,
  },
  footerLogo: {
    ...theme.typography.h3,
    color: theme.colors.text,
    marginBottom: 8,
  },
  footerText: {
    ...theme.typography.bodySm,
    color: theme.colors.textTertiary,
    marginBottom: 24,
  },
  footerLinks: {
    flexDirection: 'row',
    gap: 32,
  },
  footerLink: {
    ...theme.typography.bodySm,
    color: theme.colors.textSecondary,
  },
});

export default LandingScreen;
